name: Publish Package to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up GitHub Packages
        run: echo "//maven.pkg.github.com/${{ github.repository }}:username=${{ secrets.GITHUB_ACTOR }}:password=${{ secrets.GITHUB_TOKEN }}" > ~/.m2/settings.xml

      - name: Publish package to GitHub Packages
        run: mvn --batch-mode deploy -DrepositoryId=github -Durl=https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}