name: Publish Package to GitHub Packages
on:
  release:
    types: [ created ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: "Generate scanner and parser files"
        shell: bash
        run: |
          ./scripts/generate-parser.sh

      - name: "Publish package"
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
