name: "Build Artifacts & Draft Release"

on:
  workflow_dispatch:

jobs:
  build_and_draft_release:
    name: "Build artifacts and draft release"
    runs-on: ubuntu-24.04

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: "Generate scanner and parser files"
        shell: bash
        run: |
          ./scripts/generate-parser.sh

      - name: "Extract project version from Gradle properties"
        run: |
          echo "COMMON_VERSION=$(grep -Po 'commonVersion=\K.*' gradle.properties)" >> $GITHUB_ENV
          echo "Current Project version is: ${{ env.COMMON_VERSION }}"

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      - name: "Build with Gradle"
        run: |
          ./gradlew :java-profiler-tool:fatJar
          ./gradlew :java-profiler-fxui:distZip -Pos=win
          ./gradlew :java-profiler-fxui:distZip -Pos=linux
          ./gradlew :java-profiler-fxui:distZip -Pos=mac
          echo "created tool libraries":
          ls -l ./java-profiler-tool/build/libs/
          echo "created FxUI distributions:"
          ls -l ./java-profiler-fxui/build/distributions/

      - name: "Create release draft with assets"
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.COMMON_VERSION }}
          tag_name: v${{ env.COMMON_VERSION }}
          body: "Whats new: ..."
          draft: true
          files: |
            ./java-profiler-tool/build/libs/profiler-${{ env.COMMON_VERSION }}.jar
            ./java-profiler-fxui/build/distributions/profiler-fxui-${{ env.COMMON_VERSION }}-linux.zip
            ./java-profiler-fxui/build/distributions/profiler-fxui-${{ env.COMMON_VERSION }}-win.zip
            ./java-profiler-fxui/build/distributions/profiler-fxui-${{ env.COMMON_VERSION }}-mac.zip
