name: Run JUnit tests and upload report

on:
  push:
    branches: [ main ]

jobs:
  run_unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            prefix: "linux-"
          - os: macos-latest
            prefix: "macos-"
          - os: windows-latest
            prefix: "windows-"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Generate Scanner and Parser files
      shell: bash
      run: |
        ./scripts/generate-parser.sh

    - name: Setup and execute Gradle 'test' task
      uses: gradle/gradle-build-action@v2
      continue-on-error: true
      with:
        arguments: test

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.prefix }}test-report
        path: profiler-tool/build/reports/tests/